// react/learning_logs/src/Home.js
import React, { Component } from 'react';

class Home extends Component{
	render(){
		return (
			<div style={{textAlign:'left', padding: '0 10px'}}>
				<p><strong>Learning Log</strong></p>
				<p>Learning log helps you keep track of your learning, for any topic you''re learning about</p>
			</div>
			);
	}
}

export default Home;

// vue/learning_logs/src/components/Home.vue
<<template>  
<div>
  <h3>{{ title }}</h3>
  <h4>{{ subtitle }}</h4>
</div>
</template>
<<script>
export default {
  name: 'Home',
  data () {
    return {
      title: 'Learning Log',
      subtitle: "Learning log helps you keep track of your learning, for any topic you're learning about"
    }
  }
}
</script>
