// angular/learning-logs/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

  title = 'Learning Log'
  subtitle = "Learning log helps you keep track of your learning, for any topic you're learning about"

  constructor() { }

  ngOnInit() {
  }

}

<div class="home">
  <h3>{{title}}</h3>
  <h4>{{subtitle}}</h4>
</div>

// vue/learning_logs/src/components/Home.vue
<<template>  
<div>
  <h3>{{ title }}</h3>
  <h4>{{ subtitle }}</h4>
</div>
</template>
<<script>
export default {
  name: 'Home',
  data () {
    return {
      title: 'Learning Log',
      subtitle: "Learning log helps you keep track of your learning, for any topic you're learning about"
    }
  }
}
</script>
