// react/learning_logs/src/containers/topic.js
import React, { Component } from 'react'
import { Route, Link } from 'react-router-dom'
import { updateTopic, selectTopic } from '../actions'
import { connect } from 'react-redux'
import moment from 'moment'

class Topic extends Component{
	constructor(props){
		super(props)

        this.inputText = null
		this.updateTopic = this.updateTopic.bind(this)

		this.textarea = null
		this.addEntry = this.addEntry.bind(this);
    }
    
    componentWillMount(){        
		this.props.dispatch(selectTopic(this.props.topics, this.props.match.params.topicId))		
	}

	updateTopic(){
		if(!this.inputText || !this.inputText.value){
			return;
		}
        const { dispatch, topic, history } = this.props
        topic.text = this.inputText.value
        dispatch(updateTopic(topic)).then(()=> history.goBack())
	}

	addEntry(){
		if(!this.textarea || !this.textarea.value){
			return;
		}

		const newentry = { text: this.textarea.value, date: moment().format("YYYY-MM-DD HH:mm:ss")}
		const { topic, dispatch } = this.props
		topic.entries = topic.entries || []
		topic.entries.push(newentry)
		dispatch(updateTopic(topic)).then(()=>this.textarea.value="")
	}

	render(){		
		const add = this.props.add || false;
		const edit = this.props.edit || false;
        
        const { topic, match } = this.props
        
		const btnTxt = add ? "Add" : "Save";
		if(add || edit){
			return (
				<div>
					<input type="text" ref={input=> (this.inputText = input) && (add ? "" : input.value = topic.text) } /><button onClick={this.updateTopic}>{btnTxt}</button>
				</div>
			)
        }

		if(!topic){
			return (<div>Donot have this topic.</div>)
		}
		return (			
			<div>
				<p key={topic._id}><strong><Link to={match.url}>{topic.text}</Link></strong></p>
				<Route path={match.url} render = {()=>(
					<div>
					<ul>
					{					
						topic.entries && topic.entries.length
							? topic.entries.map(entry => (
								<li key={entry.date}>
									<p>{entry.date}</p>
									<p>{entry.text}</p>
								</li>
								))
							: <li>No entry.</li>					
					}
					</ul>
					<div>
						<textarea ref={ textarea => this.textarea = textarea } cols="50" rows="5"></textarea>
						<button onClick = {this.addEntry}>Add new entry</button>
					</div>
					</div>
				)} />
			</div>
			);
		
	}
}

const mapStateToProps = state =>{
    const { topic } = state.topicApp
    return { topic }
}

export default connect(mapStateToProps)(Topic)

// vue/learning_logs/src/components/Topic.vue
<template>
  <div class="topic">
      <div v-if="newTopic">
        <input v-model="topic.text" /><input type="button" value="Add" v-on:click="updateTopic" />
      </div>
      <div v-else-if="editTopic">
        <input v-model="topic.text" /><input type="button" value="Save" v-on:click="updateTopic" />
      </div>
      <div v-else-if="topic">      
        <p><strong>Topic: </strong>{{ topic.text }}</p>
        <ul v-if="hasEntry">
            <li v-for="entry in topic.entries" :key="entry._id">
          <p>{{ entry.date}}</p>
          <p>{{ entry.text }}</p>
        </li>
        </ul>
        <ul v-else>No entry. You can add a entry.</ul>	  
        <div>
          <textarea v-model="newentry" class="entry_text"></textarea><br/><input type="button" v-on:click="addEntry" class="addbtn" value="Add" />
        </div>
        </div>
      <div v-else>
        Do not has this topic.
      </div>      
  </div>
</template>
<script>
import { mapGetters } from 'vuex'
export default {
  name: 'Topic',
  data () {
    return { newentry: '' }
  },
  props: ['add', 'edit'],
  computed: mapGetters(['topic', 'hasEntry', 'newTopic', 'editTopic', 'updateTopicSuccess']),
  created () {
    if (this.add === true) {
      this.$store.dispatch('newtopic')
    } else if (this.edit === true) {
      const item = this.$route.params.item
      this.$store.dispatch('edittopic', item)
    } else {
      const item = this.$route.params.item
      this.$store.dispatch('showtopic', item)
    }
  },
  methods: {
    addEntry: function (e) {
      if (this.newentry) {
        const topic = this.topic
        const now = new Date()
        const date = now.getFullYear() + '-' + (now.getMonth() + 1) + '-' + now.getDate() + ' ' + now.getHours() + ':' + now.getMinutes() + ':' + now.getMinutes()
        const entry = {
          text: this.newentry,
          date: date
        }
        topic.entries = topic.entries || []
        topic.entries.push(entry)
        this.$store.dispatch('updateTopic', this.topic).then(() => {
          if (this.updateTopicSuccess) {
            this.newentry = ''
          } else {
            this.topic.entry.pop()
          }
        })
      }
    },
    updateTopic: function () {
      if (this.topic.text) {
        this.$store.dispatch('updateTopic', this.topic).then(() => {
          if (this.updateTopicSuccess) {
            this.$router.back()
          }
        })
      }
    }
  }
}
</script>
<style>
.topic {
    text-align: left;
}
.entry_text{
	width: 70%;
	height: 100px;
	margin: 10px;
}
.addbtn{
	margin-left: 10px;
	font-size: 16px;
	padding: 5px;
	width: 60px;
}
</style>
